# miniconda bootstrap from conda-forge recipe
matrix:
  fast_finish: true

environment:
  CONDA_INSTALL_LOCN: "C:\\conda"
  matrix:
    - CONDA_PY: 35
    - CONDA_PY: 27

platform:
  - x64

build: off

install:
  - appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"
  - cmd: python bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %platform% %CONDA_PY:~0,1% --without-obvci
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: pip install .[test]

test_script:
  - py.test jupyter_core
